### ISSUE TITLE
inserting data to gravity sensor

### ISSUE THREAD

**Issue by Th3ju** [thorrak/fermentrack#228]
Hi,

First of all, thank you for your great job.

I'm searching a way to insert data with an external script to my manual gravity sensors.

I've tried to send data to http://fermentrack//gravity/sensor/1?csrfmiddlewaretoken=token_found_with_burp but I'm always send to the login page. 

Did I miss something or is there another way to do that ? 

Thank you.
Juju

**Comment by thorrak** [comment]
Correct me if I'm wrong, but I think from the post you made on HBT that you were looking to integrate iSpindel, but using the "Manual Sensor" pathway. If that is the case, then awesome! iSpindel sensors are now supported natively. Update & give it a shot!

If that's not the case, let me know, and I'll see if I can find a way to make what you are looking to do work. I'm more than happy to support additional sensor types!

**Comment by Th3ju** [comment]
Hi Thorrak

That is exactly what I try to do. But not directly from iSpindle but with using @DottoreTozzi TCP-Server. because I want to send data to a mysql database AND to fermentrack.

I don't really need beer fermentation profiles based on the gravity and I just want a simple way to look at the gravity in fermentrack.

But I'm facing an authentication problem to submit datas to the "Manual Sensor" web form. Is there any token I can use ? If yes where can I find it ? 

regards,
Juju

**Comment by thorrak** [comment]
Got it. That makes sense. Let me add an API endpoint for this. Should be an easy add.

**Comment by Th3ju** [comment]
OK, I just upgrade m fermentrack and see that you integrate the iSpindle support. 
I can just use the /ispindle page to send data to fermentrack. I think another endpoint is not necessary.

2 questions : 
* which data and which format must I send ? 
* The /ispindle page is accessible by any IP and is not protected. Any chance to have a token to secure the connexion ? 

Regards
Juju

**Comment by Th3ju** [comment]
OK, I got it.

My code seems to be OK, I'll try and send a push request to @DottoreTozzi to add a FERMENTRACK option to his TCP-Server 

I'll post here after making the changes

Juju

**Comment by Th3ju** [comment]
Hi thorrak

I've just made a merge request to @DottoreTozzi. The code in my GitHub is working and sending datas to the /ispindel page.

I don't know if you finish your code but there is some problems only when fermenting log is enable  (same problem if using my forward from tcp-server or directly from my ispindel): 

`
2018-03-09 18:17:44 [19184] | Internal Server Error: /ispindel
2018-03-09 18:17:44 [19184] | Traceback (most recent call last):
2018-03-09 18:17:44 [19184] |   File "/home/fermentrack/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
2018-03-09 18:17:44 [19184] |     response = get_response(request)
2018-03-09 18:17:44 [19184] |   File "/home/fermentrack/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
2018-03-09 18:17:44 [19184] |     response = self.process_exception_by_middleware(e, request)
2018-03-09 18:17:44 [19184] |   File "/home/fermentrack/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
2018-03-09 18:17:44 [19184] |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2018-03-09 18:17:44 [19184] |   File "/home/fermentrack/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
2018-03-09 18:17:44 [19184] |     return view_func(*args, **kwargs)
2018-03-09 18:17:44 [19184] |   File "/home/fermentrack/fermentrack/gravity/views_ispindel.py", line 112, in ispindel_handler
2018-03-09 18:17:44 [19184] |     new_point.save()
2018-03-09 18:17:44 [19184] |   File "/home/fermentrack/fermentrack/gravity/models.py", line 430, in save
2018-03-09 18:17:44 [19184] |     annotation_data = self.data_point('annotation_json')
2018-03-09 18:17:44 [19184] |   File "/home/fermentrack/
2018-03-09 18:17:44 [19184] | fermentrack/gravity/models.py", line 363, in data_point
2018-03-09 18:17:44 [19184] |     retval.append({'series': 'temp', 'x': time_value, 'shortText': self.extra_data[:1],
2018-03-09 18:17:44 [19184] | TypeError: 'float' object has no attribute '__getitem__'
2018-03-09 18:17:44 [19184] | ERROR:django.request:Internal Server Error: /ispindel
2018-03-09 18:17:44 [19184] | Traceback (most recent call last):
2018-03-09 18:17:44 [19184] |   File "/home/fermentrack/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
2018-03-09 18:17:44 [19184] |     response = get_response(request)
2018-03-09 18:17:44 [19184] |   File "/home/fermentrack/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
2018-03-09 18:17:44 [19184] |     response = self.process_exception_by_middleware(e, request)
2018-03-09 18:17:44 [19184] |   File "/home/fermentrack/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
2018-03-09 18:17:44 [19184] |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2018-03-09 18:17:44 [19184] |   File "/home/fermentrack/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
2018-03-09 18:17:44 [19184] |     return view_func(*args, **kwargs)
2018-03-09 18:17:44 [19184] |   File "/home/fermentrack/fermentrack/gravity/views_ispindel.py", line 112, in ispindel_handler
2018-03-09 18:17:44 [19184] |     new_point.save()
2018-03-09 18:17:44 [19184] |   File "/home/fermentrack/fermentrack/gravity/models.py", line 430, in save
2018-03-09 18:17:44 [19184] |     annotation_data = self.data_point('annotation_json')
2018-03-09 18:17:44 [19184] |   Fil
2018-03-09 18:17:44 [19184] | e "/home/fermentrack/fermentrack/gravity/models.py", line 363, in data_point
2018-03-09 18:17:44 [19184] |     retval.append({'series': 'temp', 'x': time_value, 'shortText': self.extra_data[:1],
2018-03-09 18:17:44 [19184] | TypeError: 'float' object has no attribute '__getitem__'
`
All is OK unless you enable a "create beer and start login"

Juju

**Comment by thorrak** [comment]
Hey there!

Thanks for the merge request you made to @DottoreTozzi 's project - I appreciate it!

The bug you highlighted in your comment should now be fixed with my last push to GitHub. Please update when you get a chance, and let me know if the tracebacks disappear.

**Comment by Th3ju** [comment]
Hey !

All seem's to be OK now. No more errors and logging is ok for my iSpindel.

Thanks a lot !

Juju
