### ISSUE TITLE
upgrade failure causing fermatrac to fail to start

### ISSUE THREAD

**Issue by edtacey** [thorrak/fermentrack#478]
Hi since the last upgrade branch this fails  I re-installed recently due to similar failure and lost everything would prefer to not do so again
Have done an app-get and app-update and rebooted but the same.
it is a Pi3

Any advice would be greatly appreciated.

Error log as below.

Traceback (most recent call last):
  File "/home/fermentrack/fermentrack/utils/processmgr.py", line 24, in <module>
    application = get_wsgi_application()
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/fermentrack/venv/lib/python3.5/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/fermentrack/fermentrack/fermentrack_django/settings.py", line 270, in <module>
    import sentry_sdk
ImportError: No module named 'sentry_sdk'
Traceback (most recent call last):

**Comment by thorrak** [comment]
Hey there! I'm assuming you're running on Raspbian Stretch? If so, please see #463

**Comment by edtacey** [comment]
ok thanks for prompt response
will navigate to there

**Comment by edtacey** [comment]
the bash script sorted the issue - thanks for the support

**Comment by thorrak** [comment]
Glad to hear it worked! Let me know if you have any other issues.
